variable "environment" {}
variable "common_tags" {}
variable "aks_config" {}
variable "rg_name" {}
variable "location" {}
variable "subnet_id" {}
variable "vnet_name" {}
variable "azfw_dnat_rule_palo" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}
variable "subscription_id" {}